source 'https://rubygems.org'

gem 'rails', '3.2.11'

# this is completely ugly, however, it was the only way I could get
# - rake test
# - bundle exec rake test
# - running duck_map/test/dev.com as a normal Rails app
# to all play together in the sandbox
if ENV["RAILS_ENV"].eql?("test")
  gem 'duck_map', :require => 'duck_map', :path => File.expand_path("File.dirname(__FILE__)}/../")
else
  gem 'duck_map', :require => 'duck_map', :path => File.expand_path("File.dirname(__FILE__)}/../../../")
end

gem 'sqlite3'
